Bug Fix
Error: RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object

Cause: isolate_object_select would always try to pull the current object mode but in some cases there may be no selected/active object (IE: In the case you deleted the selected object before calling this function)

Fix: The mode is only retrieved if an object is currently selected, otherwise it's defauled to None. Assigning the passed in object is also done before any object level modes are set.