Bug Fix
Error: KeyError: 'bpy_prop_collection[key]: key "anchor" not found'

Cause: Trying to retrieve an EditBone via getEditBoneVersionOfBoneFromName when not in edit mode will cause the armature's edit_bones to be empty, as this value only exists during edit mode.

Fix: Force Edit mode before attempting to retrieve the EditBone