Bug Fix
Error: RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object

Cause: armatureObject = bpy.data.objects[0] This code would always retrieve the first object instead of retrieving the most recently created armature object. This caused actions to be performed on that object that SHOULD be performed on the new armature. And if that object were currently hidden (IE: If the user had clicked the eye/hide icon on the object) it would throw the above error message

Fix: Retrieve the currently selected armature instead. When a new armature is created, Blender's internals seem to immediately select that armature.