Bug Fix
Error: Undefined variable 'obj'

Fix: Changed obj to previously defined variable objectToUnwrap... I don't know how this never caused any errors before.